name: Hourly Update

on:
  push:
    branches:
      - master
  schedule:
    # Hourly
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: node index.js
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE: ${{ secrets.AIRTABLE_BASE }}
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
